model D2P_spring.mod;
data D2P_spring.dat;

option solver cplex;

table NegToyData IN "ODBC" "toy_dataset_2.xls" "NegToyData": NEG_SCHOOL <- [i ~ SAMPLES_NEG], {j in FEATURES} <a_neg[i,j] ~ (j)>;

read table NegToyData;


table PosToyData IN "ODBC" "toy_dataset_2.xls" "PosToyData": POS_SCHOOL <- [i ~ SAMPLES_POS], {j in FEATURES} <a_pos[i,j] ~ (j)>;

read table PosToyData;


solve;

display Correct_Classification;
